--TODO: Get upload to work for myDBoracle.sql on Omega>Oracle

DROP TABLE S20_2_RESERVES_AIRLINE;
DROP TABLE S20_2_PLANS;
DROP TABLE S20_2_TRIP_DETAILS;
DROP TABLE S20_2_AIRLINE;
DROP TABLE S20_2_EMPLOYEE;
DROP TABLE S20_2_CUSTOMER;